apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-web
  labels:
    app: todo-app-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: todo-app-web
  template:
    metadata:
      labels:
        app: todo-app-web
    spec:
      containers:
        - name: todo-app-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          envFrom: 
            - configMapRef:
                name: todo-app-web-config
 