apiVersion: v1
kind: Service
metadata:
  name: todo-app-web
  labels:
    app: todo-app-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: todo-app-web
