name: Deploy to EKS with Helm

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t 27099817/todo-app:latest .
          docker push 27099817/todo-app:latest

      # Configure AWS CLI
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Update Kubeconfig
      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name todo-app-cluster

      # Install or Upgrade Helm Chart
      - name: Deploy with Helm
        # run: |
        #   helm upgrade --install todo-app ./todo-app \
        #     --set image.repository=27099817/todo-app \
        #     --set image.tag=latest \
        #     --namespace default \
        #     --create-namespace
        run: |
          helm upgrade --install todo-app ./todo-app \
            --set image.repository=27099817/todo-app \
            --set image.tag=latest \
            --namespace default \
            --create-namespace